name: jupyter-docker

on:
  push:
    branches:
      - master

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [jupyter, jupyterlab]
        node_version: [13]
        python_version: [3.6, 3.7]
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-python${{matrix.python_version}}
          --build-arg PYTHON_VERSION=${{matrix.python_version}}
          --build-arg NODE_VERSION=${{matrix.node_version}}
          src/${{matrix.repository}}/base
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-python${{matrix.python_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:base-python${{matrix.python_version}}

  build-pyspark-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: [jupyter, jupyterlab]
        tier: [pyspark]
        python_version: [3.6, 3.7]
        spark_version: [3.0.1, 2.4.7]
    needs: build-base-image
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker build -q
          -t ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.tier}}-${{matrix.spark_version}}-python${{matrix.python_version}}
          --build-arg PYTHON_VERSION=${{matrix.python_version}}
          --build-arg SPARK_VERSION=${{matrix.spark_version}}
          src/${{matrix.repository}}/${{matrix.tier}}
      - run: docker push ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.tier}}-${{matrix.spark_version}}-python${{matrix.python_version}}
      - run: docker rmi ${{secrets.DOCKER_USERNAME}}/${{matrix.repository}}:${{matrix.tier}}-${{matrix.spark_version}}-python${{matrix.python_version}}
